import type { Metadata } from "next";
import { Outfit, Poppins, Exo_2 } from "next/font/google";
import "./globals.css";
import SideBar from "@/components/SideBar";
import { ThemeProvider } from "next-themes";
import Provider from "@/components/Provider";
import { QueryClient, QueryClientProvider } from '@tanstack/react-query';


const outfit = Outfit({ subsets: ["latin"] });

const exo = Exo_2({ subsets: ["latin"] });

const poppins = Poppins({
  weight: ["400", "500", "600", "700"], // or any weights you need
  style: ["normal"],
  display: "swap",
  subsets: ["latin-ext"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


const queryClient = new QueryClient();


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={exo.className}>
        <Provider>
          <ThemeProvider attribute="class">{children}</ThemeProvider>{" "}
        </Provider>
      </body>
    </html>
  );
}
